# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

{{- if .Values.memcached.bundled }}
{{- $livenessProbe := omit .Values.memcached.livenessProbe "enabled" }}
{{- $readinessProbe := omit .Values.memcached.readinessProbe "enabled" }}
{{- $startupProbe := omit .Values.memcached.startupProbe "enabled" }}
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-memcached
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-memcached" (include "common.names.name" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  replicas: {{ .Values.memcached.replicaCount }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-memcached" (include "common.names.name" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  {{- if .Values.memcached.updateStrategy }}
  strategy: {{- toYaml .Values.memcached.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-memcached" (include "common.names.name" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels }}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.memcached.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.memcached.affinity "context" .) | nindent 8 }}
      {{- end }}

      {{- if .Values.memcached.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.memcached.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.memcached.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.memcached.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.memcached.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.memcached.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      containers:
        - name: main
          image: "{{ coalesce .Values.memcached.image.registry .Values.global.imageRegistry }}/{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.memcached.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          {{- if .Values.memcached.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.memcached.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: memcache
              containerPort: {{ .Values.memcached.containerPort }}
              protocol: TCP
          env:
            {{- if .Values.memcached.auth.enabled }}
            - name: MEMCACHED_USERNAME
              value: {{ .Values.memcached.auth.username | quote }}
            - name: MEMCACHED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.memcached.auth.existingSecret "defaultNameSuffix" "memcached" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.memcached.auth.existingSecret "key" "memcached-password" "context" .) }}
            {{- end }}
            {{- if .Values.memcached.extraEnvVars }}
            {{ include "common.tplvalues.render" (dict "value" .Values.memcached.extraEnvVars "context" .) | nindent 12 }}
            {{- end }}
          {{- if .Values.memcached.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" $livenessProbe "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.memcached.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" $readinessProbe "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.memcached.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" $startupProbe "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.memcached.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.memcached.resources "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp
            - name: empty-dir
              mountPath: /etc/sasl2
              subPath: etc-sasl2
            - name: empty-dir
              mountPath: /var/lib/sasl2
              subPath: var-lib-sasl2
            {{- if .Values.memcached.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.memcached.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        {{- if .Values.memcached.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.memcached.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
