{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $secretName := (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "memcached" "context" .)) }}
{{- $password := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" $secretName
    "key" "memcached-password"
    "username" "nubus"
    "site" "umc-server"
    "providedValues" (list "memcached.auth.password")
    "context" .
  )
}}

{{- if and .Values.memcached.auth.enabled (not (.Values.memcached.auth.existingSecret).name) }}
---
kind: Secret
apiVersion: "v1"
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- $extraAnnotations := dict }}
  {{- if (.Values.global.secrets).keep }}
    {{- $_ := set $extraAnnotations "helm.sh/resource-policy" "keep" }}
  {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $extraAnnotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  memcached-password: {{ $password | quote }}
{{- end }}
