{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if and .Values.memcached .Values.memcached.bundled .Values.memcached.auth .Values.memcached.auth.enabled -}}
{{- $existingSecretName := "" -}}
{{- if (.Values.memcached.auth.existingSecret).name -}}
  {{- $existingSecretName = tpl (.Values.memcached.auth.existingSecret).name . -}}
{{- else if .Values.memcached.auth.existingPasswordSecret -}}
  {{- $existingSecretName = tpl .Values.memcached.auth.existingPasswordSecret . -}}
{{- end -}}
{{- if not $existingSecretName -}}
{{- $password := "" -}}
{{- if .Values.memcached.auth.password -}}
  {{- $password = .Values.memcached.auth.password -}}
{{- else -}}
  {{- $password = derivePassword 1 "long" .Release.Name "nubus" "umc-memcached-password" | sha1sum -}}
{{- end }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "memcached" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ $password | quote }}
  memcached-password: {{ $password | quote }}
{{- end -}}
{{- end }}
