{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if and .Values.memcached .Values.memcached.auth }}
{{- if not (.Values.memcached.auth.existingSecret).name }}
{{- $password := .Values.memcached.auth.password }}
{{- if not $password }}
  {{- /* Auto-generate password from release name if not provided */}}
  {{- $password = derivePassword 1 "long" .Release.Name "nubus" "umc-memcached-password" | sha1sum }}
{{- end }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "memcached" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  password: {{ $password | quote }}
{{- end }}
{{- end }}
