{{- /*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if .Values.memcached.bundled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-memcached
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-memcached" (include "common.names.name" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.memcached.service.annotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  type: {{ .Values.memcached.service.type | quote }}
  {{- if .Values.memcached.service.clusterIP }}
  clusterIP: {{ .Values.memcached.service.clusterIP }}
  {{- end }}
  {{- if .Values.memcached.service.sessionAffinity }}
  sessionAffinity: {{ .Values.memcached.service.sessionAffinity }}
  {{- end }}
  ports:
    - name: "memcache"
      port: {{ .Values.memcached.service.port }}
      targetPort: "memcache"
      protocol: TCP
  selector:
    {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-memcached" (include "common.names.name" .)) }}
    {{- merge $uiLabels $commonLabels | toYaml | nindent 4}}
{{- end }}
