---

apiVersion: "v2"
type: "application"
name: "umc-server"
description: "A Helm chart for the Univention Management Console Server"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# UMC Version
appVersion: "12.0.29"

dependencies:
  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.2.0"

...
